// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZsIkuQXDv9Bs4x3oyfS6r-83uj9P9S0',
    appId: '1:759309317281:web:511bbe8c2c0fc7801b6ce0',
    messagingSenderId: '759309317281',
    projectId: 'evently-mine',
    authDomain: 'evently-mine.firebaseapp.com',
    storageBucket: 'evently-mine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSH2jXABNKO0oUgCkIkhAl5idyJ0yScI',
    appId: '1:759309317281:android:0019b062bacd8d431b6ce0',
    messagingSenderId: '759309317281',
    projectId: 'evently-mine',
    storageBucket: 'evently-mine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7l5nHR7t0ZYgeHSp6cQr0eGJZNoZFSE',
    appId: '1:759309317281:ios:144d7e746c56ec4b1b6ce0',
    messagingSenderId: '759309317281',
    projectId: 'evently-mine',
    storageBucket: 'evently-mine.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

}